name: made-env
channels:
  - defaults
dependencies:
  - python=3.12
  - jupyter
  - matplotlib=3.8.4
  - seaborn=0.13.2
  - scipy=1.13.1
  - scikit-learn=1.4.2
  - statsmodels=0.14.2
  - pandas=2.2.1
  - numpy=1.26.4
  - requests=2.31.0
  - pytest=7.4.4
  - pytest-mock=3.10.0
  - tqdm=4.66.4

